// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client.sql

package db

import (
	"context"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (username, balance, currency, email, password_hash, provider)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING username, balance, currency, email, password_hash, provider, created_at
`

type CreateClientParams struct {
	Username     string      `json:"username"`
	Balance      int64       `json:"balance"`
	Currency     interface{} `json:"currency"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Provider     string      `json:"provider"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Username,
		arg.Balance,
		arg.Currency,
		arg.Email,
		arg.PasswordHash,
		arg.Provider,
	)
	var i Client
	err := row.Scan(
		&i.Username,
		&i.Balance,
		&i.Currency,
		&i.Email,
		&i.PasswordHash,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients
WHERE username = $1
`

func (q *Queries) DeleteClient(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteClient, username)
	return err
}

const getClient = `-- name: GetClient :one
SELECT username, balance, currency, email, password_hash, provider, created_at FROM clients
WHERE username = $1
`

func (q *Queries) GetClient(ctx context.Context, username string) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, username)
	var i Client
	err := row.Scan(
		&i.Username,
		&i.Balance,
		&i.Currency,
		&i.Email,
		&i.PasswordHash,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT username, balance, currency, email, password_hash, provider, created_at FROM clients
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListClientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.Username,
			&i.Balance,
			&i.Currency,
			&i.Email,
			&i.PasswordHash,
			&i.Provider,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientBalance = `-- name: UpdateClientBalance :one
UPDATE clients
SET balance = $2
WHERE username = $1
RETURNING username, balance, currency, email, password_hash, provider, created_at
`

type UpdateClientBalanceParams struct {
	Username string `json:"username"`
	Balance  int64  `json:"balance"`
}

func (q *Queries) UpdateClientBalance(ctx context.Context, arg UpdateClientBalanceParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientBalance, arg.Username, arg.Balance)
	var i Client
	err := row.Scan(
		&i.Username,
		&i.Balance,
		&i.Currency,
		&i.Email,
		&i.PasswordHash,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}
