// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entrie.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (client_username, amout)
VALUES ($1, $2)
RETURNING id, client_username, amout, created_at
`

type CreateEntryParams struct {
	ClientUsername pgtype.Text `json:"client_username"`
	Amout          int64       `json:"amout"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry, arg.ClientUsername, arg.Amout)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ClientUsername,
		&i.Amout,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEntry, id)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, client_username, amout, created_at FROM entries
WHERE id = $1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ClientUsername,
		&i.Amout,
		&i.CreatedAt,
	)
	return i, err
}

const listEntriesByClient = `-- name: ListEntriesByClient :many
SELECT id, client_username, amout, created_at FROM entries
WHERE client_username = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEntriesByClient(ctx context.Context, clientUsername pgtype.Text) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByClient, clientUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.ClientUsername,
			&i.Amout,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
