// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	Username     string             `json:"username"`
	Balance      int64              `json:"balance"`
	Currency     interface{}        `json:"currency"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Provider     string             `json:"provider"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Entry struct {
	ID             int64              `json:"id"`
	ClientUsername pgtype.Text        `json:"client_username"`
	Amout          int64              `json:"amout"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Transfer struct {
	ID         int64              `json:"id"`
	FromClient pgtype.Text        `json:"from_client"`
	ToClient   pgtype.Text        `json:"to_client"`
	Amout      int64              `json:"amout"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
