// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (from_client, to_client, amout)
VALUES ($1, $2, $3)
RETURNING id, from_client, to_client, amout, created_at
`

type CreateTransferParams struct {
	FromClient pgtype.Text `json:"from_client"`
	ToClient   pgtype.Text `json:"to_client"`
	Amout      int64       `json:"amount"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer, arg.FromClient, arg.ToClient, arg.Amout)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromClient,
		&i.ToClient,
		&i.Amout,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfers
WHERE id = $1
`

func (q *Queries) DeleteTransfer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTransfer, id)
	return err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, from_client, to_client, amout, created_at FROM transfers
WHERE id = $1
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromClient,
		&i.ToClient,
		&i.Amout,
		&i.CreatedAt,
	)
	return i, err
}

const listTransfersByClient = `-- name: ListTransfersByClient :many
SELECT id, from_client, to_client, amout, created_at FROM transfers
WHERE from_client = $1 OR to_client = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTransfersByClient(ctx context.Context, fromClient pgtype.Text) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByClient, fromClient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromClient,
			&i.ToClient,
			&i.Amout,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
